routes/web.php
<?php

use App\Http\Controllers\ClassesController;
use App\Http\Controllers\GradeController;
use App\Http\Controllers\StudentController;
use App\Http\Controllers\SubjectController;
use App\Http\Controllers\TeacherController;
use App\Http\Controllers\TermController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', function () {
    return view('index');
});
Route::get('admin', [GradeController::class, 'index']);
Route::group(['prefix' => 'admin'], function() {
    Route::resource('grades', GradeController::class);
    Route::resource('students', StudentController::class);
    Route::resource('teachers', TeacherController::class);
    Route::resource('subjects', SubjectController::class);
    Route::resource('terms', TermController::class);
    Route::resource('classes', ClassesController::class);
});
Route::group(['prefix' => 'data'], function() {
    Route::get('insert_class', [ClassesController::class, 'insert_class']);
    Route::get('insert_student', [StudentController::class, 'insert_student']);
    Route::get('insert_grade', [GradeController::class, 'insert_grade']);
});
Route::post('search/name', [ClassesController::class, 'getSearchAjax'])->name('search');

app/Http/Controllers/ClassesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Classes;
use Illuminate\Support\Facades\DB;

class ClassesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function insert_class(){
        $data = [
            // ['term_id'=>'1','teacher_id'=>'4','subject_id'=>'1','class_id'=>'101111'],
            // ['term_id'=>'1','teacher_id'=>'1','subject_id'=>'2','class_id'=>'101112'],
            // ['term_id'=>'1','teacher_id'=>'2','subject_id'=>'3','class_id'=>'101113'],
            // ['term_id'=>'1','teacher_id'=>'3','subject_id'=>'4','class_id'=>'101114'],
            // ['term_id'=>'1','teacher_id'=>'4','subject_id'=>'5','class_id'=>'101115'],
            // ['term_id'=>'1','teacher_id'=>'5','subject_id'=>'6','class_id'=>'101116'],
            // ['term_id'=>'2','teacher_id'=>'6','subject_id'=>'1','class_id'=>'101117'],
            // ['term_id'=>'2','teacher_id'=>'6','subject_id'=>'2','class_id'=>'101118'],
            // ['term_id'=>'3','teacher_id'=>'4','subject_id'=>'1','class_id'=>'101111'],
        ];
        Classes::insert($data);
    }
    public function index()
    {
        $classes = Classes::join('terms', 'classes.term_id', '=', 'terms.id')
        ->join('teachers', 'classes.teacher_id', '=', 'teachers.id')
        ->join('subjects', 'classes.subject_id', '=', 'subjects.id')
        ->orderBy('id', 'asc')
        ->select(['classes.*', 'terms.term_name', 'teachers.teacher_name', 'subjects.subject_name'])
        ->paginate(5);
        return view('class.class', ['classes' => $classes]);
    }

    public function getSearchAjax(Request $request)
    {
        $query = $request->get('query');
        if ($query != null) {
            $classes = Classes::join('terms', 'classes.term_id', '=', 'terms.id')
            ->join('teachers', 'classes.teacher_id', '=', 'teachers.id')
            ->join('subjects', 'classes.subject_id', '=', 'subjects.id')
            ->orWhere('class_id', 'LIKE', "%{$query}%")
            ->orWhere('term_name', 'LIKE', "%{$query}%")
            ->orWhere('teacher_name', 'LIKE', "%{$query}%")
            ->orWhere('subject_name', 'LIKE', "%{$query}%")
            ->get(['classes.*', 'terms.term_name', 'teachers.teacher_name', 'subjects.subject_name']);
            return view('class.search_class', ['classes' => $classes]);
        } elseif ($query == null) {
            $classes = Classes::join('terms', 'classes.term_id', '=', 'terms.id')
            ->join('teachers', 'classes.teacher_id', '=', 'teachers.id')
            ->join('subjects', 'classes.subject_id', '=', 'subjects.id')
            ->orderBy('id', 'asc')
            ->select(['classes.*', 'terms.term_name', 'teachers.teacher_name', 'subjects.subject_name'])
            ->paginate(5);
            return view('class.search_class', ['classes' => $classes]);
        }
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('class.add_class');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

    //  return redirect()->route('classes.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $class = Classes::join('terms', 'classes.term_id', '=', 'terms.id')
        ->join('teachers', 'classes.teacher_id', '=', 'teachers.id')
        ->join('subjects', 'classes.subject_id', '=', 'subjects.id')
        ->orderBy('id', 'asc')
        ->get(['classes.*', 'terms.term_name', 'teachers.teacher_name', 'subjects.subject_name'])
        ->find($id);
        return view('class.edit_class', [
            'class' => $class
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $class = Classes::where('id', $id)->delete();
        return redirect()->route('classes.index');
    }
}

resources/views/class/add_class.blade.php
@extends('index')
@section('content')
   <!-- body -->
   <div id="add_product">
       <div class="container">
           <div class=" row place">
               <p>Home | Product | Thêm class</p>
           </div>
           <div style="margin:40px 0 40px -15px;"><h3>Thêm class</h3></div>
           <div class="row">
               <div class="form-add">
                   <form method="post" enctype="multipart/form-data" action="{{ route('classes.store') }}">
                       {{ csrf_field() }}
                       <div class="form-group">
                           <label>Tên kì học</label>
                           <input name="term_name" type="text" value="">
                       </div>
                       <div class="form-group">
                           <label>Tên giáo viên</label>
                           <input name="teacher_name" type="text" value="">
                       </div>
                       <div class="form-group">
                           <label>Tên môn học</label>
                           <input name="subject_name" type="text" value="">
                       </div>
                       <div class="form-group">
                           <label>lớp</label>
                           <input name="class_id" type="text" value="">
                       </div>
                       <div class="form-group">
                           <input name="sbm" type="submit" value="Thêm mới">
                       </div>
                   </form>
               </div>
           </div>
       </div>
   </div>

@endsection

resources/views/class/class.blade.php
@extends('index')
@section('content')
    <div id="body">
        <div class="container">
            <a href="{{ route('classes.create') }}" class="btn btn-success btn-sm active" role="button"
               aria-pressed="true">Thêm danh mục</a>
            <div class="row content">
                <input type="text" name="classid" id="class_id" class="form-control"
                       style="width:100px;height:30px;margin-bottom:20px" placeholder="Tìm kiếm">
                <table>
                    <tr>
                        <th>ID</th>
                        <th>term_name</th>
                        <th>teacher_name</th>
                        <th>subject_name</th>
                        <th style="position:relative;">class_id</th>
                        <th>Action</th>
                    </tr>
                    <tbody id="demo">
                    </tbody>
                    <tbody id="test">
                    @foreach ($classes as $class)
                        <tr>
                            <td>{{ $class->id }}</td>
                            <td>{{ $class->term_name }}</td>
                            <td>{{ $class->teacher_name }}</td>
                            <td>{{ $class->subject_name }}</td>

                            <td style="position:relative">
                                {{ $class->class_id }}
                                <a style="position:absolute;right:0px;top:1px;padding-bottom:1px;padding-top:1px;"
                                   href="{{ route('grades.show', ['grade' => $class->id]) }}"
                                   class="btn btn-primary btn-sm active" role="button" aria-pressed="true">xem</a>
                            </td>
                            <td style="position:relative">
                                <form action="{{ route('classes.destroy', ['class' => $class->id]) }}" method="POST">
                                    <a style="position:absolute;right:60px;top:1px;padding-bottom:1px;padding-top:1px;"
                                       href="{{ route('classes.edit', ['class' => $class->id]) }}"
                                       class="btn btn-primary btn-sm active" role="button" aria-pressed="true">Sửa</a>
                                    {{ method_field('DELETE') }}
                                    {{ csrf_field() }}
                                    <button
                                        style="position:absolute;top:1px;right:0px;padding-bottom:1px;padding-top:1px;"
                                        onclick="return del('?')" class="btn btn-danger btn-sm active">Xóa
                                    </button>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
        <nav aria_label="Page navigation" style="margin:30px 0 0 75px">
            {{ $classes->links() }}
        </nav>
    </div>
@push('scripts')
    <script>
        /////////onclick delete ask/////
        function del(name) {
            return confirm("bạn có chắc chắc muốn xóa bỏ không " + name + "?");
        }

        //////// autocomplete search classid//////
        $(document).ready(function () {

            $('#class_id').keyup(function () { //bắt sự kiện keyup khi người dùng gõ từ khóa tim kiếm
                var query = $(this).val(); //lấy gía trị ng dùng gõ
                if (query != '') //kiểm tra khác rỗng thì thực hiện đoạn lệnh bên dưới
                {
                    var _token = $('input[name="_token"]').val(); // token để mã hóa dữ liệu
                    $.ajax({
                        url: "{{ route('search') }}",
                        // đường dẫn khi gửi dữ liệu đi 'search' là tên route mình đặt bạn mở route lên xem là hiểu nó là cái j.
                        method: "POST",
                        // phương thức gửi dữ liệu.
                        data: {query: query, _token: _token},
                        success: function (data) { //dữ liệu nhận về
                            $('#demo').fadeIn();
                            $('#demo').html(data); //nhận dữ liệu dạng html và gán vào cặp thẻ có id là countryList
                            $("#test").addClass('hidden')
                        }
                    });

                }
            });

        });
    </script>
@endpush
@endsection

resources/views/class/edit_class.blade.php
@extends('index')
@section('content')
  <!-- body -->
  <div id="edit_product">
      <div class="container">
          <div class=" row place">
              <p>Home | Classes | Sửa class</p>
          </div>
          <div style="margin:40px 0 40px -15px;"><h3>Sửa class</h3></div>
          <div class="row">
              <div class="form-add">
                  <form method="post" enctype="multipart/form-data" action="{{ route('classes.update', $class->id) }}">
                      @method('PUT')
                      {{csrf_field()}}
                      <div class="form-group">
                          <label>Ki Hoc</label>
                          <input name="term_name" type="text" value="{{ $class->term_name }}">
                      </div>
                      <div class="form-group">
                          <label>Ten Mon Hoc</label>
                          <input name="subject_name" type="text" value="{{ $class->subject_name }}">
                      </div>
                      <div class="form-group">
                          <label>Ten Giao Vien</label>
                          <input name="teacher_name" type="text" value="{{ $class->teacher_name }}">
                      </div>
                      <div class="form-group">
                          <label>Lop</label>
                          <input name="grade" type="text" value="{{ $class->class_id }}">
                      </div>
                      <div class="form-group">
                          <input name="sbm" type="submit" role="" value="Cập nhật">
                      </div>
                  </form>
              </div>
          </div>
      </div>
  </div>
@endsection

resources/views/class/search_class.blade.php
@foreach ($classes as $class)
    <tr>
        <td>{{ $class->id }}</td>
        <td>{{ $class->term_name }}</td>
        <td>{{ $class->teacher_name }}</td>
        <td>{{ $class->subject_name }}</td>
        <td style="position:relative">
            {{ $class->class_id }}
            <a style="position:absolute;right:0px;top:1px;padding-bottom:1px;padding-top:1px;"
               href="{{ route('grades.show', ['grade' => $class->id]) }}" class="btn btn-primary btn-sm active" role="button"
               aria-pressed="true">xem</a>
        </td>
        <td style="position:relative">
            <form action="{{ route('classes.destroy', ['grade' => $class->id]) }}" method="POST">
                <a style="position:absolute;right:60px;top:1px;padding-bottom:1px;padding-top:1px;" href="{{ route('classes.edit', ['grade' => $class->id]) }}" class="btn btn-primary btn-sm active" role="button" aria-pressed="true">Sửa</a>
                {{ method_field('DELETE') }}
                {{ csrf_field() }}
                <button style="position:absolute;top:1px;right:0px;padding-bottom:1px;padding-top:1px;" onclick="return del('{{ $class->id }}')" class="btn btn-danger btn-sm active">Xóa</button>
            </form>
        </td>
    </tr>
@endforeach
<script>
  /////////onclick delete ask/////
  function del(name){
      return confirm("bạn có chắc chắc muốn xóa bỏ không "+name+"?");
  }
</script>