routes/web.php
<?php

use App\Http\Controllers\ClassesController;
use App\Http\Controllers\GradeController;
use App\Http\Controllers\StudentController;
use App\Http\Controllers\SubjectController;
use App\Http\Controllers\TeacherController;
use App\Http\Controllers\TermController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', function () {
    return view('index');
});
Route::get('admin', [GradeController::class, 'index']);
Route::group(['prefix' => 'admin'], function() {
    Route::resource('grades', GradeController::class);
    Route::resource('students', StudentController::class);
    Route::resource('teachers', TeacherController::class);
    Route::resource('subjects', SubjectController::class);
    Route::resource('terms', TermController::class);
    Route::resource('classes', ClassesController::class);
});
Route::group(['prefix' => 'data'], function() {
    Route::get('insert_class', [ClassesController::class, 'insert_class']);
    Route::get('insert_student', [StudentController::class, 'insert_student']);
    Route::get('insert_grade', [GradeController::class, 'insert_grade']);
});
Route::post('search/name', [ClassesController::class, 'getSearchAjax'])->name('search');

app/Models/Student.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;


class student extends Model
{
    use HasFactory;
    protected $fillable = [
        'student_id',
        'student_name'
    ];
    protected $dates = ['deleted_at'];
}

app/Http/Controllers/StudentController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Student;
class StudentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function insert_student()
    {
        $data = [
            // ['student_id'=>'20176645','student_name'=>'Nguyen Van Huy'],
            // ['student_id'=>'20176646','student_name'=>'Nguyen Dinh An'],
            // ['student_id'=>'20176647','student_name'=>'Le Huy An '],
            // ['student_id'=>'20176648','student_name'=>'Le Van Sy'],
            // ['student_id'=>'20186645','student_name'=>'Dang Tuan Long'],
            // ['student_id'=>'20186655','student_name'=>'Nguyen Minh Phuong'],
            // ['student_id'=>'20196685','student_name'=>'Vu Tung Lam'],
            // ['student_id'=>'20196649','student_name'=>'Ngo Hoang Duong'],
        ];
        Student::insert($data);
        echo "thanh cong";
    }
    public function index()
    {
        $students = Student::paginate(3);
        return view('student.student',[
            'students' => $students
        ]);
    }

    function getSearchAjax(Request $request)
    {
        if($request->get('query'))
        {
            $query = $request->get('query');
            $data = Student::where('student_name', 'LIKE', "%{$query}%")
            ->get();
            $output = '<ul class="dropdown-menu" style="display:block; position:relative">';
            foreach($data as $row)
            {
               $output .= ' <li><a href="data/'. $row->id .'">'.$row->student_name.'</a></li> ';
            }
           $output .= '</ul>';
           echo $output;
       }
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
     */
    public function create()
    {
        return view('student.add_student');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $student_name = $request->input('student_name');
        Student::insert([
          'student_name' => $student_name
        ]);
        header('location:/admin/students');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
     */
    public function edit($id)
    {
        $student = Student::find($id);
        return view('student.edit_student',[
            'student' => $student
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $student = Student::find($id);
        $value = $request->input('student_name');
        $student->student_name = $value;
        $student->save();
        return redirect()->route('students.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $student = Student::where('id', $id)->delete();
        return redirect()->route('students.index');
    }
}

resources/views/student/add_student.blade.php
@extends('index')
@section('content')
   <!-- body -->
   <div id="add_product">
       <div class="container">
           <div class=" row place">
               <p>Home | Student | Thêm học sinh</p>
           </div>
           <div style="margin:40px 0 40px -15px;"><h3>Thêm học sinh</h3></div>
           <div class="row">
               <div class="form-add">
                   <form method="post" enctype="multipart/form-data" action="{{ route('students.store') }}">
                       {{csrf_field()}}
                       <div class="form-group">
                           <label>Tên học sinh</label>
                           <input name="student_name" type="text" value="">
                       </div>
                       <div class="form-group">
                           <input name="sbm" type="submit" value="Thêm mới">
                       </div>
                   </form>
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/student/edit_student.blade.php
@extends('index')
@section('content')
    <!-- body -->
    <div id="edit_cat">
        <div class="container">
            <div class=" row place">
                <p>Home | Students | Sửa tên học sinh</p>
            </div>
            <div style="margin:40px 0 40px -15px;"><h3>Sửa tên học sinh</h3></div>
            <div class="row">
                <form class="form" method="post" action="{{ route('students.update', ['student' => $student->id]) }}">
                    @method('PUT')
                    {{csrf_field()}}
                    <label>Tên học sinh</label>
                    <input name="student_name" type="" value="{{ $student->student_name }}" placeholder="Tên học sinh">
                    <input name="sbm" type="submit" value="Cập nhật">
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/student/student.blade.php
@extends('index')
@section('content')
 <!-- body -->
 <div id="body">
     <div class="container">
         <a href="{{ route('students.create') }}" class="btn btn-success btn-sm active" role="button"
            aria-pressed="true">Thêm danh mục</a>
         <div class="row content">
             <table>
                 <tr>
                     <th>id</th>
                     <th>mssv</th>
                     <th>student_name</th>
                     <th>Action</th>
                 </tr>
                 @foreach($students as $student)
                     <tr>
                         <td>{{ $student->id }} </td>
                         <td>{{ $student->student_id }} </td>
                         <td>{{ $student->student_name }}</td>
                         <td style="position:relative">
                             <a href=" {{ route('students.edit', ['student' => $student->id]) }}" class="btn btn-primary btn-sm active" role="button" aria-pressed="true">Sửa</a>
                             <form action="{{ route('students.destroy', ['student' => $student->id]) }}" method="POST">
                                 {{ method_field('DELETE') }}
                                 {{ csrf_field() }}
                                 <button onclick="return del('{{ $student->student_name }}')" style="position:absolute;top:1px;right:30px" class="btn btn-danger btn-sm active">Xóa</button>
                             </form>
                         </td>
                     </tr>
                 @endforeach
             </table>
         </div>
     </div>
     <nav aria_label="Page navigation" style="margin:30px 0 0 75px">
         {{ $students->links() }}
     </nav>
 </div>
<script>
  function del(name){
      return confirm("bạn có chắc chắc muốn xóa bỏ không "+name+"?");
  }
</script>
@endsection