routes/web.php
<?php

use App\Http\Controllers\ClassesController;
use App\Http\Controllers\GradeController;
use App\Http\Controllers\StudentController;
use App\Http\Controllers\SubjectController;
use App\Http\Controllers\TeacherController;
use App\Http\Controllers\TermController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', function () {
    return view('index');
});
Route::get('admin', [GradeController::class, 'index']);
Route::group(['prefix' => 'admin'], function() {
    Route::resource('grades', GradeController::class);
    Route::resource('students', StudentController::class);
    Route::resource('teachers', TeacherController::class);
    Route::resource('subjects', SubjectController::class);
    Route::resource('terms', TermController::class);
    Route::resource('classes', ClassesController::class);
});
Route::group(['prefix' => 'data'], function() {
    Route::get('insert_class', [ClassesController::class, 'insert_class']);
    Route::get('insert_student', [StudentController::class, 'insert_student']);
    Route::get('insert_grade', [GradeController::class, 'insert_grade']);
});
Route::post('search/name', [ClassesController::class, 'getSearchAjax'])->name('search');

app/Models/Grade.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Model;


class Grade extends Model
{
    use HasFactory;
    protected $fillable = [
        'id_student',
        'student_id',
        'student_name',
        'subject_id',
        'teacher_id',
        'term_id',
        'grade_value'
    ];
    protected $dates = ['deleted_at'];
}

app/Http/Controllers/GradeController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\GradeController as ControllersGradeController;
use Illuminate\Http\Request;
use App\Models\Grade;

class GradeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function insert_grade(){
        $data = [
            // ['class_id'=>'1','student_id'=>'1','mid_grade'=>'5','final_grade'=>'7'],
            // ['class_id'=>'1','student_id'=>'2','mid_grade'=>'6','final_grade'=>'8'],
            // ['class_id'=>'1','student_id'=>'3','mid_grade'=>'4','final_grade'=>'6'],
            // ['class_id'=>'1','student_id'=>'4','mid_grade'=>'7','final_grade'=>'6'],
            // ['class_id'=>'2','student_id'=>'1','mid_grade'=>'6','final_grade'=>'7'],
            // ['class_id'=>'2','student_id'=>'2','mid_grade'=>'9','final_grade'=>'7'],
            // ['class_id'=>'2','student_id'=>'3','mid_grade'=>'7','final_grade'=>'6'],
            // ['class_id'=>'2','student_id'=>'4','mid_grade'=>'3','final_grade'=>'6'],
            // ['class_id'=>'3','student_id'=>'2','mid_grade'=>'6','final_grade'=>'3'],
            // ['class_id'=>'3','student_id'=>'3','mid_grade'=>'6','final_grade'=>'6'],
            // ['class_id'=>'3','student_id'=>'4','mid_grade'=>'7','final_grade'=>'3'],
            // ['class_id'=>'3','student_id'=>'5','mid_grade'=>'6','final_grade'=>'7'],
            // ['class_id'=>'4','student_id'=>'3','mid_grade'=>'10','final_grade'=>'6'],
            // ['class_id'=>'4','student_id'=>'4','mid_grade'=>'7','final_grade'=>'1'],
            // ['class_id'=>'4','student_id'=>'5','mid_grade'=>'10','final_grade'=>'6'],
            // ['class_id'=>'4','student_id'=>'6','mid_grade'=>'6','final_grade'=>'8'],
            // ['class_id'=>'5','student_id'=>'1','mid_grade'=>'8','final_grade'=>'9'],
            // ['class_id'=>'5','student_id'=>'2','mid_grade'=>'8','final_grade'=>'5'],
            // ['class_id'=>'5','student_id'=>'3','mid_grade'=>'6','final_grade'=>'2'],
            // ['class_id'=>'5','student_id'=>'4','mid_grade'=>'5','final_grade'=>'6'],
            // ['class_id'=>'5','student_id'=>'5','mid_grade'=>'7','final_grade'=>'7'],
            // ['class_id'=>'5','student_id'=>'6','mid_grade'=>'6','final_grade'=>'6'],
            // ['class_id'=>'6','student_id'=>'1','mid_grade'=>'6','final_grade'=>'4'],
            // ['class_id'=>'6','student_id'=>'2','mid_grade'=>'8','final_grade'=>'6'],
            // ['class_id'=>'6','student_id'=>'3','mid_grade'=>'6','final_grade'=>'2'],
            // ['class_id'=>'6','student_id'=>'4','mid_grade'=>'9','final_grade'=>'7'],
            // ['class_id'=>'6','student_id'=>'5','mid_grade'=>'6','final_grade'=>'3'],
            // ['class_id'=>'6','student_id'=>'6','mid_grade'=>'1','final_grade'=>'6'],
            // ['class_id'=>'6','student_id'=>'7','mid_grade'=>'7','final_grade'=>'7'],
            // ['class_id'=>'6','student_id'=>'8','mid_grade'=>'6','final_grade'=>'3'],
            // ['class_id'=>'7','student_id'=>'1','mid_grade'=>'7','final_grade'=>'6'],
            // ['class_id'=>'7','student_id'=>'2','mid_grade'=>'6','final_grade'=>'4'],
            // ['class_id'=>'7','student_id'=>'3','mid_grade'=>'9','final_grade'=>'7'],
            // ['class_id'=>'7','student_id'=>'4','mid_grade'=>'2','final_grade'=>'6'],
            // ['class_id'=>'8','student_id'=>'2','mid_grade'=>'7','final_grade'=>'7'],
            // ['class_id'=>'8','student_id'=>'4','mid_grade'=>'2','final_grade'=>'9'],
            // ['class_id'=>'8','student_id'=>'6','mid_grade'=>'7','final_grade'=>'9'],
            // ['class_id'=>'8','student_id'=>'8','mid_grade'=>'8','final_grade'=>'6'],
            // ['class_id'=>'9','student_id'=>'5','mid_grade'=>'6','final_grade'=>'7'],
            // ['class_id'=>'9','student_id'=>'6','mid_grade'=>'7','final_grade'=>'8'],
            // ['class_id'=>'9','student_id'=>'7','mid_grade'=>'6','final_grade'=>'6'],
            // ['class_id'=>'9','student_id'=>'8','mid_grade'=>'6','final_grade'=>'6'],
        ];
        Grade::insert($data);
        echo "thanh cong";
    }
    public function index()
    {

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('grade.add_grade');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $student_name = $request->input('student_name');
        $subject_name = $request->input('subject_name');
        $teacher_name = $request->input('teacher_name');
        $term = $request->input('term');
        $grade = $request->input('grade');
        switch ($subject_name) {
            case "Thong Tin So 1":
                $subject_id = 2;
                break;
            case "Kien Truc May Tinh":
                $subject_id = 1;
                break;
            case "Xu Ly So Tin Hieu":
                $subject_id = 4;
                break;
            case "Thiet Ke So VHDL":
                $subject_id = 6;
                break;
            case "Mach Tuyen Tinh 2":
                $subject_id = 2;
                break;
            case "Co So Mang ":
                $subject_id = 5;
                break;
            default :
                $subject_id = null;
        }
        switch ($teacher_name) {
            case "Ngo Vu Duc":
                $teacher_id = 3;
                break;
            case "Ta Thi Kim Hue":
                $teacher_id = 1;
                break;
            case "Pham Van Tien":
                $teacher_id = 2;
                break;
            case "Vu Van Yem":
                $teacher_id = 4;
                break;
            case "Cung Thanh Long":
                $teacher_id = 5;
                break;
            case "Nguyen Viet Anh":
                $teacher_id = 6;
                break;
            default :
                $teacher_id = null;
        }
        switch ($term) {
            case "Ki 1":
                $term_id = 1;
                break;
            case "Ki 2":
                $term_id = 2;
                break;
            case "Ki 3":
                $term_id = 3;
                break;
            default :
                $term_id = null;
        }
        Grade::insert([
            'student_name' => $student_name,
            'subject_id' => $subject_id,
            'teacher_id' => $teacher_id,
            'term_id' => $term_id,
            'grade_value' => $grade
        ]);
        return redirect()->route('grades.index');
    }


    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
     */
    public function show($id, Request $request)
    {
        $searchGrades = Grade::query()
            ->where('grades.class_id', $id)
            ->leftJoin('students', 'grades.student_id', '=', 'students.id')
            ->leftJoin('classes', 'grades.class_id', '=', 'classes.id')
            ->leftJoin('terms', 'classes.term_id', '=', 'terms.id')
            ->select(['grades.*', 'students.student_name', 'students.student_id', 'classes.class_id', 'terms.term_name']);
        if ($request->filled('student_id')) {
            $searchGrades->where('students.student_id', 'like', '%'. $request->input('student_id') .'%');
        }
        if ($request->filled('student_name')) {
            $searchGrades->where('students.student_name', 'like', '%'. $request->input('student_name') .'%');
        }
        $grades = $searchGrades->orderByDesc('grades.id')->paginate(20);
        return view('grade.grade', [
            'grades' => $grades,
            'id' => $id
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
     */
    public function edit($id)
    {
        $grade = Grade::query()
            ->where('grades.id', $id)
            ->leftJoin('students', 'grades.student_id', '=', 'students.id')
            ->leftJoin('classes', 'grades.class_id', '=', 'classes.id')
            ->leftJoin('terms', 'classes.term_id', '=', 'terms.id')
            ->select(['grades.*', 'students.student_name', 'teachers.teacher_name', 'terms.term_name']);
        return view('grade.edit_grade', [
            'grade' => $grade
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $student_name = $request->input('student_name');
        $subject_name = $request->input('subject_name');
        $teacher_name = $request->input('teacher_name');
        $term = $request->input('term');
        $grade_value = $request->input('grade');

        switch ($subject_name) {
            case "Thong Tin So 1":
                $subject_id = 2;
                break;
            case "Kien Truc May Tinh":
                $subject_id = 1;
                break;
            case "Xu Ly So Tin Hieu":
                $subject_id = 4;
                break;
            case "Thiet Ke So VHDL":
                $subject_id = 6;
                break;
            case "Mach Tuyen Tinh 2":
                $subject_id = 2;
                break;
            case "Co So Mang ":
                $subject_id = 5;
                break;
            default:
                $subject_id = null;
        }
        switch ($teacher_name) {
            case "Ngo Vu Duc":

resources/views/grade/add_grade.blade.php
@extends('index')
@section('content')
   <!-- body -->
   <div id="add_product">
       <div class="container">
           <div class=" row place">
               <p>Home | Product | Thêm sản phẩm</p>
           </div>
           <div style="margin:40px 0 40px -15px;"><h3>Thêm sản phẩm</h3></div>
           <div class="row">
               <div class="form-add">
                   <form method="post" enctype="multipart/form-data" action="{{ route('grades.store') }}">
                       {{csrf_field()}}
                       <div class="form-group">
                           <label>Tên học sinh</label>
                           <input name="student_name" type="text" value="">
                       </div>
                       <div class="form-group">
                           <label>Tên môn học</label>
                           <input name="subject_name" type="text" value="">
                       </div>
                       <div class="form-group">
                           <label>Tên giáo viên</label>
                           <input name="teacher_name" type="text" value="">
                       </div>
                       <div class="form-group">
                           <label>kì học</label>
                           <input name="term" type="text" value="">
                       </div>
                       <div class="form-group">
                           <label>Điểm</label>
                           <input name="grade" type="text" value="">
                       </div>
                       <div class="form-group">
                           <input name="sbm" type="submit" value="Thêm mới">
                       </div>
                   </form>
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/grade/edit_grade.blade.php
@extends('index')
@section('content')

  <!-- body -->
  <div id="edit_product">
        <div class="container">
            <div class=" row place">
                <p>Home | Grade | Sửa điểm</p>
            </div>
            <div style="margin:40px 0 40px -15px;"><h3>Sửa điểm</h3></div>
            <div class="row">
                <div class="form-add">
                    <form method="post" enctype="multipart/form-data" action="{{  route('grades.update', $grade->id) }}">
                    @method('PUT')
                    {{csrf_field()}}
                        <div class="form-group">
                            <label>Ten Hoc Sinh</label>
                            <input name="student_name" type="text" value="{{ $grade->student_id }}">
                        </div>
                        <div class="form-group">
                            <label>Ten Mon Hoc</label>
                            <input name="subject_name" type="text" value="{{ $grade->student_name }}">
                        </div>
                        <div class="form-group">
                            <label>Ki Hoc</label>
                            <input name="term" type="text" value="{{ $grade->term_name }}">
                        </div>
                        <div class="form-group">
                            <label>Diem</label>
                            <input name="grade" type="text" value="{{ $grade->mid_grade }}">
                        </div>
                        <div class="form-group">
                            <input name="sbm" type="submit" role="" value="Cập nhật">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/grade/grade.blade.php
@extends('index')
@section('content')

    <div id="body">
        <div class="container">
            <a href="{{ route('grades.create') }}" class="btn btn-success btn-sm active" role="button" aria-pressed="true">Thêm sản phẩm</a>
            <form action="{{ route('grades.show', ['grade' => $id]) }}">
                <div class="row">
                    <div class="col-lg-2">
                        <div class="form-group">
                            <label>MSSV</label>
                            <input type="text" name="student_id" id="student_id" value="{{ request('student_id')?request('student_id'):'' }}" class="form-control">
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="form-group">
                            <label>Tên sinh viên</label>
                            <input type="text" name="student_name" id="student_name"
                                   value="{{ request('student_name')?request('student_name'):'' }}"
                                   class="form-control">
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <label></label>
                        <button type="submit" class="btn btn-info" style="margin-top:32px">Tìm kiếm</button>
                    </div>
                </div>
            </form>
            <div class="row content">
                <table>
                    <tr>
                        <th>id</th>
                        <th>id_student</th>
                        <th>student_name</th>
                        <th>class</th>
                        <th>term</th>
                        <th>mid_grade</th>
                        <th>final_grade</th>
                        <th>grade</th>
                        <th>Action</th>
                    </tr>
                    @foreach ( $grades as $grade )
                        <tr>
                            <td>{{ $grade->id }}</td>
                            <td>{{ $grade->student_id }}</td>
                            <td>{{ $grade->student_name }}</td>
                            <td>{{ $grade->class_id }}</td>
                            <td>{{ $grade->term_name }}</td>
                            <td>{{ $grade->mid_grade }}</td>
                            <td>{{ $grade->final_grade }}</td>
                            <td>{{ null }}</td>
                            <td style="position:relative">
                                <a style="position:absolute;right:60px;top:1px;padding-bottom:1px;padding-top:1px;"
                                   href="{{ route('grades.edit', ['grade' => $grade->id]) }}" class="btn btn-primary btn-sm active" role="button" aria-pressed="true">Sửa</a>
                                <form action="{{ route('grades.destroy', ['grade' => $grade->id]) }}" method="POST">
                                    {{ method_field('DELETE') }}
                                    {{ csrf_field() }}
                                    <button
                                        style="position:absolute;top:1px;right:10px;padding-bottom:1px;padding-top:1px;"
                                        onclick="return del(' {{ $grade->grade_name }} ')"
                                        class="btn btn-danger btn-sm active">Xóa
                                    </button>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                </table>
            </div>
            {{ $grades->appends(request()->query())->links() }}
        </div>
    </div>
    <script>
        function del(name) {
            return confirm("bạn có chắc chắc muốn xóa bỏ không " + name + "?");
        }
    </script>
@endsection